In [1]:
import tensorflow as tf

In [2]:
import numpy as np

In [3]:
from tensorflow import keras

In [4]:
print(tf.__version__)

2.11.0


In [5]:
print('shub')

shub


In [6]:
#create tensor with tf.constant()
scaler = tf.constant(7)

In [7]:
scaler

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [8]:
scaler.ndim

0

In [9]:
vector = tf.constant(7)

In [10]:
vector

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [11]:
vector = tf.constant([10,10])

In [12]:
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10])>

In [13]:
vector.ndim

1

In [14]:
matrix = tf.constant([[1,2],[7,5]])

In [15]:
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [7, 5]])>

In [16]:
matrix.ndim

2

In [17]:
tf.Variable

tensorflow.python.ops.variables.Variable

In [18]:
a = tf.random.Generator.from_seed(42)
a=a.normal(shape=(3,3))
b = tf.random.Generator.from_seed(42)
b=b.normal(shape=(3,3))


a,b,a==b

(<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702,  0.07595026],
        [-1.2573844 , -0.23193763, -1.8107855 ],
        [ 0.09988727, -0.50998646, -0.7535805 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 3), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702,  0.07595026],
        [-1.2573844 , -0.23193763, -1.8107855 ],
        [ 0.09988727, -0.50998646, -0.7535805 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 3), dtype=bool, numpy=
 array([[ True,  True,  True],
        [ True,  True,  True],
        [ True,  True,  True]])>)

In [19]:
not_shuffled = tf.constant([[1,2],[5,4],[8,5]])
not_shuffled

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[1, 2],
       [5, 4],
       [8, 5]])>

In [20]:
tf.random.shuffle(not_shuffled)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[5, 4],
       [1, 2],
       [8, 5]])>

In [21]:
tf.random.set_seed(20)
tf.random.shuffle(not_shuffled,seed=20)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[8, 5],
       [5, 4],
       [1, 2]])>

In [22]:
import numpy as np

In [23]:
num_a = np.arange(1,25,dtype=int)

In [24]:
num_a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

In [25]:
a1 = tf.constant(num_a,shape=(2,3,4))
b1 = tf.constant(num_a)

a1,b1

(<tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
 array([[[ 1,  2,  3,  4],
         [ 5,  6,  7,  8],
         [ 9, 10, 11, 12]],
 
        [[13, 14, 15, 16],
         [17, 18, 19, 20],
         [21, 22, 23, 24]]])>,
 <tf.Tensor: shape=(24,), dtype=int32, numpy=
 array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24])>)

In [26]:
rank_4 = tf.zeros(shape=(2,3,4,5))
rank_4

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [27]:
rank_4[0,1]

<tf.Tensor: shape=(4, 5), dtype=float32, numpy=
array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]], dtype=float32)>

In [28]:
rank_4[:2,:2,:2,:2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

In [29]:
tf.expand_dims(rank_4,axis=1)

<tf.Tensor: shape=(2, 1, 3, 4, 5), dtype=float32, numpy=
array([[[[[0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.]],

         [[0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.]],

         [[0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.]]]],



       [[[[0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.]],

         [[0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.]],

         [[0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.]]]]], dtype=float32)>

In [30]:
d=tf.constant([-1,-2])
d

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([-1, -2])>

In [31]:
tf.abs(d)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([1, 2])>

In [32]:
e = tf.constant(np.random.randint(1,100,80))
e

<tf.Tensor: shape=(80,), dtype=int32, numpy=
array([38, 62, 40, 60, 66, 15, 68, 39,  3, 63, 16, 74, 48, 82, 97, 69, 45,
        3, 21, 66, 23, 82, 84, 14,  9, 37, 33, 19, 30, 86, 53, 43, 77, 25,
       35, 40, 60, 25, 74, 69, 93, 38, 48, 50, 64, 21, 37, 38, 26, 34, 70,
       91, 39, 76,  5, 26, 46, 10, 92, 57, 24, 38, 17, 73, 68, 86, 64, 31,
       97, 63, 65, 43, 69, 51, 28, 73, 51, 97, 97, 34])>

In [33]:
tf.size(e),e.shape,e.ndim

(<tf.Tensor: shape=(), dtype=int32, numpy=80>, TensorShape([80]), 1)

In [34]:
tf.reduce_min(e)

<tf.Tensor: shape=(), dtype=int32, numpy=3>

In [35]:
tf.reduce_max(e)

<tf.Tensor: shape=(), dtype=int32, numpy=97>

In [36]:
tf.reduce_sum(e)

<tf.Tensor: shape=(), dtype=int32, numpy=4023>

In [37]:
tf.reduce_mean(e)

<tf.Tensor: shape=(), dtype=int32, numpy=50>

In [38]:
import tensorflow_probability as tfp

In [39]:
tfp.stats.variance(e)

<tf.Tensor: shape=(), dtype=int32, numpy=653>

In [40]:
#positional maximum amd minimum

In [45]:
tf.random.set_seed(42)
f=tf.random.uniform(shape=[80])
f

<tf.Tensor: shape=(80,), dtype=float32, numpy=
array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
       0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
       0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
       0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
       0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
       0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
       0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
       0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
       0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
       0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043,
       0.6073899 , 0.46523476, 0.97803545, 0.7223145 , 0.32347047,
       0.82577336, 0.4976915 , 0.19483674, 0.7588748 , 0.3380444 ,
       0.28128064, 0.31513572, 0.60670924, 0.7498598 , 0.5016055 ,
       0.18282163, 0.13179815, 0.64636123, 0.9559475 , 0.6670735 ,
       0.307555

In [46]:
#positional maximum
tf.argmax(f)

<tf.Tensor: shape=(), dtype=int64, numpy=52>

In [47]:
f[tf.argmax(f)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.97803545>

In [48]:
tf.reduce_max(f)

<tf.Tensor: shape=(), dtype=float32, numpy=0.97803545>

In [49]:
#positional minimum
tf.argmin(f)

<tf.Tensor: shape=(), dtype=int64, numpy=16>

In [50]:
f[tf.argmin(f)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.009463668>

In [51]:
## squeezing a tensor (removing all single dimmensions)

In [57]:
tf.random.set_seed(42)
g = tf.constant(tf.random.uniform(shape=[50]), shape=(1,1,1,1,50))
g

<tf.Tensor: shape=(1, 1, 1, 1, 50), dtype=float32, numpy=
array([[[[[0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
           0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
           0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
           0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
           0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
           0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
           0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
           0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
           0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
           0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043]]]]],
      dtype=float32)>

In [58]:
g.shape

TensorShape([1, 1, 1, 1, 50])

In [59]:
g_squeez = tf.squeeze(g)
g_squeez,g_squeez.shape

(<tf.Tensor: shape=(50,), dtype=float32, numpy=
 array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
        0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
        0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
        0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
        0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
        0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
        0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
        0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
        0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
        0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
       dtype=float32)>,
 TensorShape([50]))

In [67]:
li = [1,2,3,4,5]
tf.one_hot(li,depth=6)

<tf.Tensor: shape=(5, 6), dtype=float32, numpy=
array([[0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]], dtype=float32)>

In [68]:
#Finding access to GPU
tf.config.list_physical_devices()

[PhysicalDevice(name='/physical_device:CPU:0', device_type='CPU')]